apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: mywebapp
  labels:
    name: web
    app: mywebapp
spec:
  selector:
    name: web
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
#spec:
#  selector:
#    name: web
#  type: ClusterIP
#  ports:
#    - name: http
#      port: 80
#      targetPort: 80
#      protocol: TCP