apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: mywebapp
  labels:
    name: web
    app: mywebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      terminationGracePeriodSeconds: 30
        containers:
            - name: web
              image: melodyvn2020/simple-devops-image:latest
              imagePullPolicy: "Always"
              ports:
                - containerPort: 8080

#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: nginx-deployment
#  namespace: web
#spec:
#  selector:
#    matchLabels:
#      app: nginx
#  replicas: 2
#  template:
#    metadata:
#      labels:
#        app: nginx
#    spec:
#      containers:
#        - name: nginx
#          image: bharamicrosystems/nginx:v1
#          ports:
#            - containerPort: 80